export const dataEn = {
  0: {
    questions: [
      {
        id: 1,
        title: "Which gesture is very often taken by a photographer ?",
        correctReplies: ["Ok", "Hi", "Kiss", "Heart", "Peace", "Middle finger"],
        repliesScores: ["27", "19", "16", " 13", "10", "5"],
      },
      {
        id: 2,
        title: "How can hockey skates be used on a desert island?",
        correctReplies: [
          "Instead of a knife / saw",
          "Crush / break nuts",
          "Axe / chop down trees",
          "Shoes",
          "To strike a spark",
          "Like a razor",
        ],
        repliesScores: ["21", "12", "9", " 8", "7", "6"],
      },
      {
        id: 3,
        title: "What confused the border guard in the movie star's passport?",
        correctReplies: [
          "Age",
          "Other surname / first name",
          "Photo",
          "Other appearance",
          "Place of birth",
          "No place for a visa",
        ],
        repliesScores: ["29", "24", "15", " 6", "5", "3"],
      },
      {
        id: 4,
        title:
          "Who is it?- the husband asks menacingly. What does the wife say?",
        correctReplies: [
          "Relative",
          "Colleague",
          "Your son",
          "Boggart",
          "Cat",
          "How do I know?",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
      {
        id: 5,
        title: "",
        correctReplies: [
          "Высоцкий",
          "Окуджава",
          "Розенбаум",
          " Цой",
          "Антонов",
          "Макаревич",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
    ],
  },

  1: {
    questions: [
      {
        id: 1,
        title: "You saw a former classmate on TV. who has he become?",
        correctReplies: [
          "Newscaster",
          "Sportsman",
          "Journalist",
          "Astronaut",
          "Politician",
          "Actor",
        ],
        repliesScores: ["27", "19", "16", " 13", "10", "5"],
      },
      {
        id: 2,
        title:
          "The choice of what, according to the woman, is the most difficult?",
        correctReplies: [
          "Husband / father of children",
          "Dresses / outfits",
          "Perfumes / Perfumes",
          "Colors of lipstick",
          "Baby name",
          "Profession",
        ],
        repliesScores: ["23", "20", "10", " 6", "5", "4"],
      },
      {
        id: 3,
        title:
          '"Here is your first serious document," the parents told the child. What is it about?',
        correctReplies: [
          "Student planner",
          "Birth certificate",
          "Certificate",
          "Passport",
          "Social card / travel card",
          "School pass",
        ],
        repliesScores: ["30", "18", "14", "9", "6", "4"],
      },
      {
        id: 4,
        title: "What, besides love, did The Beatles sing about?",
        correctReplies: [
          "About the world",
          "About the yellow submarine",
          "About girls",
          "About the bird",
          "About yesterday",
          "About the USSR",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
      {
        id: 5,
        title: "",
        correctReplies: [
          "Высоцкий",
          "Окуджава",
          "Розенбаум",
          " Цой",
          "Антонов",
          "Макаревич",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
    ],
  },
  2: {
    questions: [
      {
        id: 1,
        title: "Five people inspect the building. Who are they?",
        correctReplies: [
          "Tourists / excursion",
          "Admission Committee",
          "Buyers",
          "Builders / architect",
          "Robbers",
          "Tenants",
        ],
        repliesScores: ["21", "15", "11", "9", "5", "3"],
      },
      {
        id: 2,
        title: "The boxer lost this fight. Why is everyone congratulating him?",
        correctReplies: [
          "For courage",
          "Stayed alive",
          "Dishonestly judged",
          "Last fight",
          "He's a local",
          "It's his birthday",
        ],
        repliesScores: ["26", "21", "12", "10", "8", "6"],
      },
      {
        id: 3,
        title: "Who uses a towel at work?",
        correctReplies: [
          "Cook",
          "Hairdresser",
          "Doctor",
          "Waiter",
          "Athlete",
          "The bath attendant",
        ],
        repliesScores: ["20", "16", "14", "9", "8", "7"],
      },
      {
        id: 4,
        title: "What is the name of the place where everyone becomes happy?",
        correctReplies: [
          "Paradise",
          "Registry office",
          "Your home",
          "Resort",
          "Maternity hospital",
          "Toilet",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
      {
        id: 5,
        title: "",
        correctReplies: [
          "Высоцкий",
          "Окуджава",
          "Розенбаум",
          " Цой",
          "Антонов",
          "Макаревич",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
    ],
  },
  3: {
    questions: [
      {
        id: 1,
        title:
          "Why does a person celebrate his birthday on different days of the month?",
        correctReplies: [
          "Born on February 29",
          "On a day off",
          "With different companies",
          "Does not know the exact date",
          "Works on a shift basis",
          'Was born "for the second time"',
        ],
        repliesScores: ["24", "16", "10", "7", "4", "3"],
      },
      {
        id: 2,
        title: "What changes in a woman after the wedding?",
        correctReplies: [
          "Character",
          "Surname",
          "Status",
          "Figure",
          "Mood",
          "Life",
        ],
        repliesScores: ["24", "16", "15", "8", "5", "4"],
      },
      {
        id: 3,
        title: "The most effective remedy for constant falling in love?",
        correctReplies: [
          "Marriage",
          "Work",
          "Alcohol",
          "Love",
          "Sleep",
          "Time",
        ],
        repliesScores: ["35", "17", "12", "10", "8", "5"],
      },
      {
        id: 4,
        title: "What has man lost in the process of evolution?",
        correctReplies: [
          "Tail",
          "Wool",
          "Freedom",
          "Conscience",
          "Health",
          "Connection with nature",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
      {
        id: 5,
        title: "",
        correctReplies: [
          "Высоцкий",
          "Окуджава",
          "Розенбаум",
          " Цой",
          "Антонов",
          "Макаревич",
        ],
        repliesScores: ["15", "30", "60", " 120", "180", "240"],
      },
    ],
  },
};
